messages = {
    "céu limpo": [
        "Assim como o céu limpo, você é um raio de sol na minha vida.",
        "Com você, tudo fica mais claro do que um céu limpo em um dia de verão.",
        "Seu brilho é tão intenso quanto o sol em um céu limpo.",
        "Você é a estrela que ilumina o meu céu limpo todas as noites.",
        "Seu sorriso é como o sol em um céu limpo, aquecendo meu coração.",
    ],
    "nuvens dispersas": [
        "Assim como as nuvens dispersas, minha mente se enche de pensamentos sobre você.",
        "Você é como uma nuvem dispersa em um céu azul, fazendo meu coração voar.",
        "A incerteza das nuvens dispersas é como a paixão que sinto por você.",
        "Você é a nuvem que veio para alegrar o meu dia, mesmo em meio a outras nuvens dispersas.",
        "As nuvens dispersas são como o mistério que me cerca quando penso em você.",
    ],
    "nublado": [
        "O céu nublado é como a minha mente quando penso em você, cheia de mistério e desejo.",
        "Assim como as nuvens, a nossa paixão se forma e se desfaz, mas nunca desaparece.",
        "Os dias nublados me lembram da nossa história de amor, cheia de altos e baixos, mas sempre emocionante.",
        "As nuvens no céu refletem o fogo que arde em mim quando estou ao seu lado.",
        "A sensação de acolhimento e proteção que as nuvens trazem é como o seu abraço, me envolvendo e me fazendo sentir segura.",
        "O clima nublado é perfeito para ficar debaixo das cobertas com você, aproveitando o aconchego do seu corpo.",
        "A atmosfera nublada é como a tensão elétrica entre nós, prometendo momentos intensos e apaixonados.",
        "Assim como as nuvens, a nossa história de amor está sempre mudando, mas o nosso amor é constante.",
        "Os dias nublados me inspiram a buscar calor e conforto em você, meu porto seguro.",
        "As nuvens no céu são como um lembrete do quão bela é a nossa jornada juntos, mesmo nos momentos mais sombrios.",
    ],
    "chuva leve": [
        "Hmmm... parece que a chuva resolveu dar o ar da graça. Que tal um guarda-chuva e eu para te aquecer?",
        "A chuva chegou de mansinho... assim como eu. Vamos nos aquecer juntos?",
        "Que tal se abrigar da chuva comigo? Vou te dar um motivo para esquecer do mau tempo.",
        "A chuva está caindo como gotas de paixão. Vamos curtir esse clima juntos?",
        "A chuva está me dando boas ideias... Você não quer fazer parte delas?",
        "Com a chuva caindo lá fora, vamos criar nosso próprio clima quente aqui dentro.",
        "A chuva está lavando tudo lá fora, mas aqui dentro podemos nos aquecer juntos.",
        "A chuva está deixando tudo molhado... inclusive eu. Vamos aproveitar esse clima juntos?",
        "Com a chuva caindo, é hora de encontrar um abrigo... e eu posso ser o seu.",
    ],
    "algumas nuvens": [
        "As nuvens estão dançando pelo céu, assim como eu posso dançar nos seus pensamentos.",
        "As nuvens estão brincando de esconder e buscar... assim como eu posso brincar de esconder e buscar com você.",
        "As nuvens estão fazendo uma coreografia sensual no céu... assim como eu posso fazer uma coreografia sensual em sua mente.",
        "As nuvens estão enfeitando o céu com seu charme... assim como eu posso enfeitar seus pensamentos com meu charme.",
        "As nuvens estão pintando o céu com tons de mistério... assim como eu posso pintar sua imaginação com tons de sedução.",
        "As nuvens estão deixando o céu ainda mais sexy... assim como eu posso deixar nossos momentos ainda mais excitantes.",
        "As nuvens estão jogando de esconde-esconde com o sol... assim como eu posso jogar de esconde-esconde com você em minha mente.",
        "As nuvens estão acrescentando um toque de mistério ao céu... assim como eu posso acrescentar um toque de sedução ao nosso encontro.",
    ],
    "névoa": [
        "Os flocos de neve estão caindo suavemente do céu, assim como eu posso cair suavemente em seus braços.",
        "A neve está cobrindo tudo com sua pureza e beleza... assim como eu posso cobrir você com meu afeto e carinho.",
        "A neve está trazendo um ar de romantismo ao ar... assim como eu posso trazer um ar de sedução com meu olhar.",
        "Os flocos de neve estão dançando no ar, assim como eu posso dançar em seus sonhos mais secretos.",
        "A neve está criando um cenário perfeito para momentos aconchegantes... assim como eu posso criar um cenário perfeito para momentos íntimos.",
        "A neve está transformando o mundo em um conto de fadas... assim como eu posso transformar nossa história em uma aventura excitante.",
        "A neve está criando um ambiente mágico e encantador... assim como eu posso criar um ambiente sedutor e apaixonante.",
        "A neve está caindo com suavidade e elegância... assim como eu posso cair em seus braços com delicadeza e desejo.",
    ]
}
